package com.example.demo.jsonprocessing;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.util.List;

class WeatherDtoResponseDeserializerTest {
    String input = """
            [
              {
                "name": "Kyiv",
                "local_names": {
                  "cs": "Kyjev",
                  "vo": "Küyiv",
                  "an": "Kyiv",
                  "sl": "Kijev",
                  "ga": "Cív",
                  "gl": "Kiev",
                  "he": "קייב",
                  "lt": "Kijevas",
                  "tt": "Киев",
                  "cu": "Кꙑѥвъ",
                  "ie": "Kyiv",
                  "tl": "Kiev",
                  "mr": "क्यीव",
                  "bo": "ཀིབ།",
                  "da": "Kyiv",
                  "ln": "Kyjiw",
                  "ta": "கீவ்",
                  "ascii": "Kyiv",
                  "no": "Kyiv",
                  "eu": "Kiev",
                  "yo": "Kiev",
                  "bn": "কিয়েভ",
                  "ku": "Kîev",
                  "te": "క్యివ్",
                  "am": "ኪየቭ",
                  "kn": "ಕೀವ್",
                  "cy": "Kyiv",
                  "gd": "Kyiv",
                  "os": "Киев",
                  "hi": "कीव",
                  "hr": "Kijiv",
                  "az": "Kiyev",
                  "nl": "Kiev",
                  "ky": "Киев",
                  "zu": "IKiyevi",
                  "mk": "Кијив",
                  "ab": "Кыив",
                  "vi": "Kyiv",
                  "af": "Kyiv",
                  "uk": "Київ",
                  "ms": "Kiev",
                  "fr": "Kiev",
                  "fa": "کی‌یف",
                  "en": "Kyiv",
                  "fo": "Kyiv",
                  "ia": "Kiev",
                  "bg": "Киев",
                  "eo": "Kijivo",
                  "kk": "Киев",
                  "lb": "Kiew",
                  "oc": "Kyiiv",
                  "tw": "Kiev",
                  "pa": "ਕੀਵ",
                  "ml": "കീവ്",
                  "la": "Kiovia",
                  "sc": "Kiev",
                  "ca": "Kíiv",
                  "be": "Кіеў",
                  "et": "Kõjiv",
                  "br": "Kyiv",
                  "fy": "Kiev",
                  "sr": "Кијев",
                  "id": "Kyiv",
                  "uz": "Kiyev",
                  "ht": "Kyèv",
                  "ro": "Kiev",
                  "hu": "Kijev",
                  "bs": "Kijev",
                  "cv": "Кийӳ",
                  "tg": "Киев",
                  "th": "เคียฟ",
                  "zh": "基辅",
                  "gv": "Kyiv",
                  "mn": "Киев",
                  "hy": "Կիև",
                  "qu": "Kiyiw",
                  "it": "Kiev",
                  "yi": "קיעוו",
                  "kl": "Kyiv",
                  "sv": "Kyiv",
                  "mi": "Kieu",
                  "pt": "Kiev",
                  "pl": "Kijów",
                  "ru": "Киев",
                  "fi": "Kiova",
                  "ja": "キーウ",
                  "ko": "키이우",
                  "sk": "Kyjev",
                  "wo": "Kiyew",
                  "is": "Kænugarður",
                  "ar": "كييف",
                  "my": "ကီးယက်မြို့",
                  "ur": "کیف",
                  "kv": "Киев",
                  "feature_name": "Kyiv",
                  "es": "Kiev",
                  "de": "Kiew",
                  "ka": "კიევი",
                  "ug": "كىيېۋ",
                  "tr": "Kıyiv",
                  "mt": "Kjiv",
                  "sq": "Kievi",
                  "ba": "Киев",
                  "se": "Kiova",
                  "bi": "Kyiv",
                  "sh": "Kyiv",
                  "nn": "Kiev",
                  "sw": "Kiev",
                  "io": "Kyiv",
                  "el": "Κίεβο",
                  "lv": "Kijiva",
                  "jv": "Kyiv"
                },
                "lat": 50.4500336,
                "lon": 30.5241361,
                "country": "UA"
              }
            ]
            """;
    @Test
    void shouldDeserializeWeatherObject() throws Exception {
        var objectMapper = new ObjectMapper();
        var actual = objectMapper.readValue(input, new TypeReference<List<WeatherDtoResponse>>() {});
        actual.forEach(System.out::println);
    }
}